# Generated by Django 5.0.3 on 2024-07-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meli_code',
            field=models.CharField(default='123', max_length=10),
            preserve_default=False,
        ),
    ]
