# Generated by Django 5.0.4 on 2024-07-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'کمپانی ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'محصولات'},
        ),
    ]
