# Generated by Django 5.0.6 on 2024-06-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_read_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
