# Generated by Django 5.0.3 on 2024-07-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'پیام ها'},
        ),
    ]
