# Generated by Django 5.0.3 on 2024-07-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
    ]
