# Generated by Django 5.0.4 on 2024-07-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Single_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.FloatField(null=True)),
                ('views', models.IntegerField()),
                ('slug', models.SlugField()),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
