# Generated by Django 5.0.4 on 2024-07-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_blog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
