# Generated by Django 5.0.4 on 2024-07-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_single_blog_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
